[package]
name = "dusk-pki"
version = "0.4.1"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network"]
edition = "2018"

[dependencies]
rand_core = "0.6"
dusk-bls12_381 = {git="https://github.com/dusk-network/bls12_381", branch="vlopes11/g1affine-raw-bytes", default-features=false}
dusk-jubjub = {git="https://github.com/dusk-network/jubjub", branch="vlopes11/g1affine-unchecked-bytes", default-features=false}
poseidon252 = {git="https://github.com/dusk-network/Poseidon252", branch="vlopes11/bump-plonk", default-features=false}
hex = {version = "^0.4", default-features = false}
subtle = {version = "^2.2.1", default-features = false}
canonical = {version = "0.4", optional = true}
canonical_derive = {version = "0.4", optional = true}
rand = {version="0.8", optional = true}
sha2 = {version="0.8", optional = true}

[features]
default = ["std"]
std = [
    "dusk-jubjub/default",
    "dusk-bls12_381/default",
    "poseidon252/default",
    "subtle/default",
    "hex/default",
    "rand/default",
    "sha2/default"
]
canon = [
    "canonical",
    "canonical_derive",
    "dusk-bls12_381/canon",
    "dusk-jubjub/canon"
]
