[package]
name = "dusk-pki"
version = "0.3.0"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network"]
edition = "2018"

[dependencies]
poseidon252 = { git = "https://github.com/dusk-network/Poseidon252", tag = "v0.13.2"}
dusk-jubjub = "0.5"
canonical = {version = "0.4", optional = true}
canonical_derive = {version = "0.4", optional = true}
hex = "^0.4"
rand = "^0.7"
sha2 = "0.8"
anyhow = "1.0"
thiserror = "1.0"

[dependencies.subtle]
version = "^2.2.1"
default-features = false

[features]
canon = ["canonical", "canonical_derive", "dusk-jubjub/canon", "poseidon252/canon"]
