[package]
name = "dusk-pki"
version = "0.4.1"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network"]
edition = "2018"

[dependencies]
rand_core = "0.5.1"
dusk-jubjub = "0.5"
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.14.1", default-features = false}
hex ="^0.4"
subtle = "^2.2.1"
canonical = {version = "0.4", optional = true}
canonical_derive = {version = "0.4", optional = true}

[dev-dependencies]
rand ="0.7"
sha2 = "0.8"

[features]
canon = [
    "canonical",
    "canonical_derive",
    "dusk-jubjub/canon"
]
